//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiOkulBilgiSistem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veliler
    {
        public int VeliNo { get; set; }
        public string VeliAdSoyad { get; set; }
        public string OgrenciAdSoyadi { get; set; }
        public string Yakinlik { get; set; }
        public string EgitimDurumu { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
    }
}
